using System;
using System.Diagnostics;
using System.IO;
using Microsoft.Office.Interop.Word;

namespace ChordSheetConverter
{
    public class DocxToPdfConverter
    {
        private string _libreOfficePath = @"C:\Program Files\LibreOffice\program\soffice.exe"; // Adjust this if LibreOffice is installed elsewhere

        // Method to check if Microsoft Word is installed
        public bool IsWordInstalled()
        {
            try
            {
                // Check if Word Interop can be accessed
                Type wordType = Type.GetTypeFromProgID("Word.Application");
                return wordType != null;
            }
            catch
            {
                return false;
            }
        }

        // Method to check if LibreOffice is installed
        public bool IsLibreOfficeInstalled()
        {
            return File.Exists(_libreOfficePath);
        }

        // Main method to convert DOCX to PDF using Word or LibreOffice
        public void convertDocxToPdf(string docxFilePath, string pdfOutputPath)
        {
            if (IsWordInstalled())
            {
                convertDocxToPdfUsingWord(docxFilePath, pdfOutputPath);
            }
            else if (IsLibreOfficeInstalled())
            {
                convertDocxToPdfUsingLibreOffice(docxFilePath, pdfOutputPath);
            }
            else
            {
                throw new Exception("Neither Microsoft Word nor LibreOffice is installed.");
            }
        }

        // Method to convert DOCX to PDF using Microsoft Word
        private static void convertDocxToPdfUsingWord(string docxFilePath, string pdfOutputPath)
        {
            Application wordApp = new Application();
            try
            {
                Document wordDoc = wordApp.Documents.Open(docxFilePath);
                wordDoc.SaveAs2(pdfOutputPath, WdSaveFormat.wdFormatPDF);
                wordDoc.Close();
            }
            catch (Exception ex)
            {
                throw new Exception("Error converting DOCX to PDF using Microsoft Word: " + ex.Message);
            }
            finally
            {
                wordApp.Quit();
            }
        }

        // Method to convert DOCX to PDF using LibreOffice
        private void convertDocxToPdfUsingLibreOffice(string docxFilePath, string pdfOutputPath)
        {
            string outputDirectory = Path.GetDirectoryName(pdfOutputPath);

            try
            {
                // Step 1: Convert DOCX to PDF using LibreOffice
                ProcessStartInfo libreOfficeProcess = new ProcessStartInfo
                {
                    FileName = _libreOfficePath,
                    Arguments = $"--headless --convert-to pdf \"{docxFilePath}\" --outdir \"{outputDirectory}\"",
                    CreateNoWindow = true,
                    UseShellExecute = false
                };
                using (Process process = Process.Start(libreOfficeProcess))
                {
                    process.WaitForExit();
                }

                // Verify if the PDF was created
                if (!File.Exists(pdfOutputPath))
                {
                    throw new Exception("PDF file not generated by LibreOffice.");
                }
            }
            catch (Exception ex)
            {
                throw new Exception("Error converting DOCX to PDF using LibreOffice: " + ex.Message);
            }
        }
    }

}
